export const RECORD_USERINFO = 'RECORD_USERINFO'
export const New_loginStatus = 'New_loginStatus'
export const New_loginPower = 'New_loginPower'
export const New_makerCertSN = 'New_makerCertSN'
export const New_ValidateCode = 'New_ValidateCode'